### ISSUE TITLE
Partial behaviour changed

### ISSUE THREAD

**Issue by glitch59** [Shardj/zf1-future#328] opened 2023-02-21 15:24 UTC
Hi,

First of all: thanks for creating this fork! It saves us a lot of work in keeping old projects running at the latest version of PHP.

However, since version 1.22.0, we have noticed a change in the behavior of the way view->partial passes parameters to the partial.

For example, inside a template called index.phtml we use:
`echo $this->partial('content.phtml', $this);`

Until version 1.21.4 all parameters set in any controller with view->assign, where passed to the partial via the second argument. Also to nested partials; content.phtml in this example. But as of version 1.22.0 this no longer works.

For example if we set view->assign('pageTitle', 'My page') and we echo $this->pageTitle in content.phtml, it was available. 
But as of 1.22.0, this no longer works. $this->pageTitle is set in index.phtml, but no longer in content.phtml.

Is this intentionally, or is it a bug?

I know it is not best practice, but we have a project that depends on this inheritance throughout all templates, and it uses these variables that are passed on. If this no longer works, all templates must be rewritten and each variable must be defined when calling partial. Lot of work, so I'm looking for a way to keep things as they are and allow the variables to be passed on like they where until the last update.

For now, we have pinned the version to 1.21.4 and all works well again, but of course, that's not the preferred solution.

Is there maybe a solution for this?

Please let me know.
Thanks!

**Comment by hungtrinh** [comment] 2023-02-24 07:45
### Root cause

Partial behaviour changed after merged PR https://github.com/Shardj/zf1-future/pull/268#issuecomment-1300536420

Lost effected of code line 114. What I feared happened @VentyCZ 
``` 114                $view->assign(get_object_vars($model)); ```
https://github.com/Shardj/zf1-future/blob/5446af3466d1fc3faa32a708af2cdc9baf9fc11a/library/Zend/View/Helper/Partial.php#L74-L120

**Closed** 2023-02-27 08:10 UTC

**Comment by glitch59** [comment] 2023-02-27 10:59
Tested and confirmed as resolved. Thank you!

**Comment by staabm** [comment] 2023-04-11 13:17
would be great to get a new release as the latest one does no work for us because of this BC break it contains.
