### ISSUE TITLE
Zend_Date - no exception for invalid date format?

### ISSUE THREAD

**Issue by sreichel** [Shardj/zf1-future#339] opened 2023-04-02 08:44 UTC
`2014-05` isnt a valid date, but before https://github.com/Shardj/zf1-future/commit/c7a5cf6dcd36bffefd7dd30e68db49b35966bee1 an exception was thrown ... now it returns 1/1970

```
Fatal error:  Uncaught Zend_Date_Exception: unsupported ISO8601 format (2014-05) in /var/www/html/vendor/shardj/zf1-future/library/Zend/Date.php:1960
Stack trace:
#0 /var/www/html/vendor/shardj/zf1-future/library/Zend/Date.php(1003): Zend_Date->_calculate('set', '2014-05', 'c', 'en_US')
#1 /var/www/html/vendor/shardj/zf1-future/library/Zend/Date.php(197): Zend_Date->set('2014-05', 'c', 'en_US')
#2 /var/www/html/test.php(13): Zend_Date->__construct('2014-05', 'c', 'en_US')
#3 {main}
  thrown in /var/www/html/vendor/shardj/zf1-future/library/Zend/Date.php on line 1960
```

Test:

```php
# output format
$format = 'M/y';
$locale = 'en_US';

# current behavoir - does not work, returns 1/1970
$date = '2014-05';
$part = Zend_Date::ISO_8601;
$date = new Zend_Date($date, $part, $locale);
$test = $date->toString($format);
```

**Comment by glensc** [comment] 2023-04-02 09:15
that commit belongs to original zf1:
- https://github.com/zendframework/zf1/pull/450

**Comment by sreichel** [comment] 2023-04-02 10:28
`2014` becomes `20` and `14` here ....

```
                // (T)hhmm
                if (empty($timematch)) {
                    preg_match('/[T,\s]{0,1}(\d{2})(\d{2})/', $tmpdate, $timematch);
                }
```

**Comment by develart-projects** [comment] 2023-08-10 16:17
`if (empty($datematch) && empty($timematch)) {
                    require_once 'Zend/Date/Exception.php';
                    throw new Zend_Date_Exception("unsupported ISO8601 format ($date)", 0, null, $date);
                }`

**Comment by develart-projects** [comment] 2023-08-10 16:46
The problem is, that time part of matching pattern is still validating full entered string, not just time part. Together with AND condition above it's resulting in wrong validation. That's the root cause.

Imo we have to change condition to OR, if we have to really validate ISO format and that's exactly what I'm going to do.

**Comment by develart-projects** [comment] 2023-08-10 17:22
But that is not passing tests:
```
2) Zend_DateTest::testSet2
Zend_Date_Exception: unsupported ISO8601 format (2007-10-20)

/usr/share/NetBeansProjects/ZF1-Future/library/Zend/Date.php:1959
/usr/share/NetBeansProjects/ZF1-Future/library/Zend/Date.php:1002
/usr/share/NetBeansProjects/ZF1-Future/tests/Zend/DateTest.php:1984
/usr/share/NetBeansProjects/ZF1-Future/tests/resources/Runner.php:20
/usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php:72
/usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php:111

3) Zend_DateTest::testTimezone
Zend_Date_Exception: unsupported ISO8601 format (01.01.2000T00:00:00Z)

/usr/share/NetBeansProjects/ZF1-Future/library/Zend/Date.php:1959
/usr/share/NetBeansProjects/ZF1-Future/library/Zend/Date.php:1002
/usr/share/NetBeansProjects/ZF1-Future/library/Zend/Date.php:197
/usr/share/NetBeansProjects/ZF1-Future/tests/Zend/DateTest.php:4018
/usr/share/NetBeansProjects/ZF1-Future/tests/resources/Runner.php:20
/usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php:72
/usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php:111
```

..seems like time part is optional in this format, therefore we have to find another way.

**Comment by develart-projects** [comment] 2023-08-10 18:30
Only possibility is to pre-check the date lenghts. It's not bulletproof, but it's addressing your problem.
Fixed in https://github.com/Shardj/zf1-future/pull/364

**Comment by develart-projects** [comment] 2023-08-10 19:12
1.23.0 released

**Closed by develart-projects** 2023-08-10 19:12 UTC
Labels: bug, to be released
